intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += gsl%lib{gsl}

./: lib{caramel}: {mxx hxx cxx}{** -version} \
  hxx{version} $impl_libs $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBCARAMEL_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBCARAMEL_SHARED_BUILD

# Export options.
#
lib{caramel}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{caramel}: cxx.export.poptions += -DLIBCARAMEL_STATIC
libs{caramel}: cxx.export.poptions += -DLIBCARAMEL_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{caramel}: bin.lib.version = @"-$version.project_id"
else
  lib{caramel}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the libcaramel/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{mxx hxx}{*}:
{
  install         = include/libcaramel/
  install.subdirs = true
}
